rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-18mode
    - rvm: jruby-19mode
